#pragma once
#include "Class_Client.h"
#include "Class_Client_or_Server.h"
#include "Class_Game_over.h"
#include "Class_Information.h"
#include "Class_Menu.h"
#include "Class_Network.h"
#include "Class_Option.h"
#include "Class_Realization.h"
#include "Class_Screensaver.h"
#include "Class_Server.h"
#include "Class_Studies.h"
#include <time.h>
#include <iostream>
#include <Windows.h>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>